package com.miternos.messaging;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2016-01-02T13:01:55.294+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebServiceClient(name = "MessagingService", 
                  wsdlLocation = "file:/home/miternos/dev/github/jetty-ws-server-mock/src/main/wsdl/MessagingService.wsdl",
                  targetNamespace = "http://messaging.miternos.com/") 
public class MessagingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://messaging.miternos.com/", "MessagingService");
    public final static QName MessagingPort = new QName("http://messaging.miternos.com/", "MessagingPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/miternos/dev/github/jetty-ws-server-mock/src/main/wsdl/MessagingService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MessagingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/miternos/dev/github/jetty-ws-server-mock/src/main/wsdl/MessagingService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MessagingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MessagingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessagingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessagingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessagingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MessagingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns Messaging
     */
    @WebEndpoint(name = "MessagingPort")
    public Messaging getMessagingPort() {
        return super.getPort(MessagingPort, Messaging.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Messaging
     */
    @WebEndpoint(name = "MessagingPort")
    public Messaging getMessagingPort(WebServiceFeature... features) {
        return super.getPort(MessagingPort, Messaging.class, features);
    }

}
