package com.miternos.messaging;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.1
 * 2016-01-02T13:01:55.268+02:00
 * Generated source version: 2.4.1
 * 
 */
@WebService(targetNamespace = "http://messaging.miternos.com/", name = "Messaging")
@XmlSeeAlso({ObjectFactory.class})
public interface Messaging {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "send", targetNamespace = "http://messaging.miternos.com/", className = "com.miternos.messaging.Send")
    @WebMethod(action = "send")
    @ResponseWrapper(localName = "sendResponse", targetNamespace = "http://messaging.miternos.com/", className = "com.miternos.messaging.SendResponse")
    public com.miternos.messaging.SendMessageResponse send(
        @WebParam(name = "sender", targetNamespace = "")
        com.miternos.messaging.Sender sender,
        @WebParam(name = "receiverMsisdn", targetNamespace = "")
        java.lang.String receiverMsisdn,
        @WebParam(name = "message", targetNamespace = "")
        com.miternos.messaging.Message message,
        @WebParam(name = "transactionId", targetNamespace = "")
        java.lang.String transactionId,
        @WebParam(name = "reportingEntity", targetNamespace = "")
        com.miternos.messaging.ReportingEntity reportingEntity
    );
}
